package com.lit.fire.flame.nlq.audit;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.lit.fire.flame.nlq.config.AskEngineProperties;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.lang.Nullable;
import org.springframework.stereotype.Component;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;

/**
 * Records each time the mathematician layer had to ask the LLM to compute a formula that is not in the
 * deterministic code catalog (F14): a structured JSON log line always, plus — when
 * {@code aura.ask.formula-gap.persist=true} (the default) — a row in a table in AuraMath's <b>own</b>
 * database. The accumulated rows are the backlog of formulas to implement in code in a later release.
 *
 * <p>Mirrors {@link AskAuditLogger}: the application {@link JdbcTemplate} is injected {@code @Nullable},
 * the internal table is auto-created, and any persistence failure is swallowed with a warning so a
 * logging problem never breaks the request. It records structure only — no credentials, and no raw row
 * values beyond the single computed figure.
 */
@Component
public class FormulaGapLogger {

    private static final Logger log = LoggerFactory.getLogger(FormulaGapLogger.class);

    private final AskEngineProperties properties;
    private final JdbcTemplate appJdbcTemplate;
    private final Gson gson = new Gson();
    private final boolean tableReady;

    @Autowired
    public FormulaGapLogger(AskEngineProperties properties, @Nullable JdbcTemplate appJdbcTemplate) {
        this.properties = properties;
        this.appJdbcTemplate = appJdbcTemplate;
        this.tableReady = ensureTable();
    }

    /** Emit one formula-gap record: always a JSON log line, and (when enabled) a persisted row. Never throws. */
    public void record(FormulaGapRecord record) {
        if (record == null) {
            return;
        }
        try {
            log.info("{}", gson.toJson(toJson(record)));
        } catch (RuntimeException e) {
            log.warn("failed to write formula-gap log line for request {}", record.getRequestId());
        }
        if (properties.getFormulaGap().isPersist()) {
            persist(record);
        }
    }

    private JsonObject toJson(FormulaGapRecord r) {
        JsonObject o = new JsonObject();
        o.addProperty("event", "ask.formula_gap");
        o.addProperty("requestId", r.getRequestId());
        addIfPresent(o, "question", r.getQuestion());
        addIfPresent(o, "formulaName", r.getFormulaName());
        addIfPresent(o, "formulaDescription", r.getFormulaDescription());
        addIfPresent(o, "expression", r.getExpression());
        JsonArray columns = new JsonArray();
        for (String c : r.getColumns()) {
            columns.add(c);
        }
        o.add("columns", columns);
        if (r.getComputedValue() != null) {
            o.addProperty("computedValue", r.getComputedValue());
        }
        return o;
    }

    private void persist(FormulaGapRecord r) {
        if (!tableReady) {
            return;
        }
        String table = properties.getFormulaGap().getTable();
        String sql = "INSERT INTO " + table + " ("
                + "request_id, created_at, question, formula_name, formula_description, expression, "
                + "columns, computed_value) VALUES (?,?,?,?,?,?,?,?)";
        try {
            appJdbcTemplate.update(sql,
                    r.getRequestId(),
                    Timestamp.from(Instant.now()),
                    r.getQuestion(),
                    r.getFormulaName(),
                    r.getFormulaDescription(),
                    r.getExpression(),
                    join(r.getColumns()),
                    r.getComputedValue());
        } catch (RuntimeException e) {
            log.warn("failed to persist formula-gap row for request {} into table {}: {}",
                    r.getRequestId(), table, e.getClass().getSimpleName());
        }
    }

    private boolean ensureTable() {
        if (!properties.getFormulaGap().isPersist() || appJdbcTemplate == null) {
            return false;
        }
        String table = properties.getFormulaGap().getTable();
        try {
            appJdbcTemplate.execute("CREATE TABLE IF NOT EXISTS " + table + " ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "request_id VARCHAR(64), "
                    + "created_at TIMESTAMP, "
                    + "question TEXT, "
                    + "formula_name VARCHAR(128), "
                    + "formula_description TEXT, "
                    + "expression TEXT, "
                    + "columns TEXT, "
                    + "computed_value DOUBLE PRECISION)");
            return true;
        } catch (RuntimeException e) {
            log.warn("formula-gap logging: could not ensure table {} exists ({}); logging to the log "
                    + "line only", table, e.getClass().getSimpleName());
            return false;
        }
    }

    private static void addIfPresent(JsonObject o, String key, String value) {
        if (value != null) {
            o.addProperty(key, value);
        }
    }

    @Nullable
    private static String join(List<String> values) {
        if (values == null || values.isEmpty()) {
            return null;
        }
        return String.join(",", values);
    }
}
